name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 */2 * *'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: fregante/setup-git-user@v2
      - name: Try updating the version
        run: ./scripts/bump-and-publish.sh
