name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 5,19 * *'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: fregante/setup-git-user@v2
      - name: Try updating the version
        run: ./scripts/bump-and-publish.sh
      - run: git push --follow-tags
